### ISSUE TITLE
Login redirect page?

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#13]
Hey, Just a suggestion and bug I want to send in, I'll be posting anymore I find via this.

Firstly the suggestion is to add in a redirect page. This will be used for so say you're not logged in & looking at the forums, you go to login and then it brings you to a redirect area, "you have logged in successfully! please wait % of seconds while we redirect you to _users previous viewing area_

Lastly the bug was, when I tried to view my donation page via your forum software (using BuyCraft) it gave me a blank screen, mainly because I wasn't logged in, takes me to the login screen and then when I went to login nothing apart from a white screen it shown, can be viewed from here: http://prntscr.com/6xjaoc

Regards,
Lilmac12312

P.s: If you need any help with the software I'd be happy to help, such could be advertising it(own a youtube with 1.9k) so on so forth.

**Comment by samerton** [comment]
Hi,

I've added the redirect page to the [todo list](https://github.com/samerton/NamelessMC/wiki/Features).

As for the blank page on the Donate page, could you please enable error reporting in inc/init.php and see if an error message then appears on the Donate page?

Thanks,
Sam.

**Comment by Lilmac12312** [comment]
@samerton How exactly do I enable the error reporting within the inc/init.php?

Edit: Never mind got it working.

**Comment by Lilmac12312** [comment]
Gives me this on donate page when I'm not logged in: http://prntscr.com/6xxqnj

Gives me this on the donate page when I'm logged in: http://prntscr.com/6xxqt6

**Comment by samerton** [comment]
Fixed the fatal error in [latest commit](https://github.com/samerton/NamelessMC/commit/33238536a402440323ffca1966e6642e4f1184f5). Please replace the contents of your pages/donate.php with the contents of [this file](https://raw.githubusercontent.com/samerton/NamelessMC/master/pages/donate.php).

As for the notice and warning errors, you'll need to head into the Donate tab of the Admin panel and click "Synchronise with Web Store". This will populate the donate page with your webstore's packages.

**Comment by Lilmac12312** [comment]
Seems to be working fine now. Also @samerton http://prntscr.com/6y5bl2

**Comment by samerton** [comment]
@Lilmac12312 Fixed in this [commit](https://github.com/samerton/NamelessMC/commit/36467e0151686d894358043bef2844985c9f1e1a). Again, please replace the contents of pages/donate.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/master/pages/donate.php). Thanks for spotting these!

**Comment by Lilmac12312** [comment]
No problem man. Did you ever read or think about what I said about help with the software?

**Comment by samerton** [comment]
Indeed, I'd really appreciate it if you were able to help spread the word about the software. Thanks for the offer!
