### ISSUE TITLE
Groups & in-game registration / rank gathering

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#14]
Will there be some sort of implementation of the software being able to grab your in-game rank and applying it onto the forums, this would only apply if you have registered on the forums?

Also would a feature such as /register & /resetpassword be added into a plugin which we can use on our server(s)?

Lastly will there be a more easier and or clear way of creating more groups on the forums?

**Comment by Root3287** [comment]
I am making a plugin on that this will work on both web and server side.

**Comment by samerton** [comment]
I've planned for ingame registration to be included in a plugin for a while now, and it'll definitely be released in the future. 
Synchronisation between ingame ranks and forum ranks will hopefully be done by the plugin, however I could probably implement something now using a MySQL permissions plugin such as PermissionsEX.

The only thing I have planned for forum groups so far is the ability to set permissions inheritance. Which other improvements do you have in mind?

**Comment by Lilmac12312** [comment]
Well for the MySQL backend of PermissionsEX I found it very buggy and also extremely laggy when trying to use it on my server(s).

For group improvements I was somewhat thinking about pre-made group labels/banners, like what Xenforo offers when creating a new group. 

It would also be neat to display something such as this on the users profile, letting them to be able to add in their steam, twitter, youtube etc and then have the option to disable adding any of those within the AdminCP. Also colored forum names

**Comment by ghost** [comment]
Thanks for the suggestion, a /register plugin is in the works with group sync and a ticket system. I will look into adding a resetpassword into the plugin, possibly expand it to grab more information about the user in the future that can be accessed via /profile but just an idea for now

**Comment by samerton** [comment]
Registration + group sync added in the plugin (still in-dev, the repo is [here](https://github.com/NamelessMC/Nameless-Plugin)).
