### ISSUE TITLE
Color customization 

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#17]
Would be neat to be able to change the color of the this, that etc so for example you're able to change the colour of this: http://minecorner.net/s/0WUKdX.png (the blue around the news message)

**Comment by samerton** [comment]
This'll be more down to custom themes/templates which are unlikely to be added any time soon instead of a built-in "editor". For now it's possible to edit the HTML or .css files manually.

**Comment by samerton** [comment]
Custom templates and themes are now included in the latest 1.0 developments, found in the new repository [here](https://github.com/NamelessMC/Nameless).
