### ISSUE TITLE
Staff page 

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#18]
Many "custom" forums we see nowadays use their own way of gather staff ranks via in-game and I feel this would be something beneficial that many of us could make use out of, supports for GroupManager, PermissionsEX etc would have to be added etc.

**Comment by samerton** [comment]
I wasn't originally going to create a dedicated staff page as they could be added with the upcoming custom pages, however if group syncing via a plugin can be added, I'll add a staff page which automatically updates depending on the group syncing.

**Comment by Lilmac12312** [comment]
Sounds good, hopefully someone is nice enough to help out with that

**Comment by samerton** [comment]
This was added in the new repo and will be included in version 1.0.10
