### ISSUE TITLE
Add in colour support & HTML / Youtube videos

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#19]
There should be an option where you're able to insert youtube videos along with HTML code & color support for coloring words within threads etc.

**Comment by samerton** [comment]
Thanks, added in the [latest commit](https://github.com/samerton/NamelessMC/commit/8af17aaf610141269cb206550aaf2d9b2d7ea8df). You'll have to replace your entire assets/js folder with the latest assets/js folder from the Github download.

**Comment by samerton** [comment]
Changing the colour of text implemented in [this commit](https://github.com/samerton/NamelessMC/commit/8234b6bb16ca588157635642ad8991709cb36129).
