### ISSUE TITLE
Multiple account making

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#20]
Users are able to make multiple accounts off the same email. http://prntscr.com/6ztjvy

Hopefully we can see this fixed within the next update along with a way to prevent multiple accounts being made on the same IP too but this may cause conflict with those who have legitimate siblings who also play on the server.

**Comment by samerton** [comment]
I might add an option in the future to enable locking one account to an IP, but as you say this may cause issues.

**Comment by Lilmac12312** [comment]
At the most I feel only having one account per email till a solution is bought up about the IP situation
