### ISSUE TITLE
Non-registered username

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#21]
So I'm not exactly sure how this happened but the user called "Gankinq" has made an account on the website yet it displays his name as such: http://prntscr.com/70knvn but when I click the exact username it displays their profile page: http://prntscr.com/70ko24

**Comment by samerton** [comment]
There's an option to enable custom usernames which must have been selected during installation. This can be disabled in the admin panel's General Settings section, however there are currently issues when it's disabled which I need to work on.

**Comment by Lilmac12312** [comment]
@samerton I don't have this enabled so I have no idea what the issue could be, a fix for this would be great once it's figured out http://minecorner.net/s/1RhQad.png

**Comment by samerton** [comment]
I'll work on this now, thanks.

**Comment by Lilmac12312** [comment]
@samerton Thanks man, appreciate it.

**Comment by samerton** [comment]
Should be fixed in [latest commit](https://github.com/samerton/NamelessMC/commit/3e97c33bf0be85e54fc5d862fac31ea1949bc534).
