### ISSUE TITLE
Head players in Play page

### ISSUE THREAD

**Issue by elraro** [samerton/NamelessMC#22]
The query server dont get the info about online players (names players).

Example: http://beta.elbloqueyelcubo.es/play/

(i do a print_r($Info) and u can see the array). U can loggin and test: 188.165.254.55

**Comment by samerton** [comment]
Due to how the query works, if you're using a Bungee instance you'll need to define all of the sub-servers in your network in the Admin panel. 
An example is [the demo](http://demo.worldscapemc.co.uk/play/), where the "Survival" and "Creative" servers are both part of a Bungee network.
