### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#23]
Does or will the forums support 1.8 namechanges? Say someone has the name aaabbb and has an account on the forum then changes their name to aaabbc would it automatically update?

Secondly do you plan on making this project a premium source later on once it begins to become a bigger task? I know you did mention that you're wanting to give back to the community but this is more than giving back in my eyes.

**Comment by samerton** [comment]
The system to update all users' Minecraft names at once isn't quite ready yet. Even when it is, it probably won't be fully automatic, it will rely on a user created cron job.
For now you need to head into the Users page in the Admin panel, select a user, click the Tasks button in the top right, then click "Update Minecraft Name". Obviously this isn't ideal as it only updates that user's Minecraft name.

It'll always remain as an open source project, maybe in the future some sort of hosting option could be introduced, similar to Enjin or Vanilla Forums' hosting platform.

**Comment by Lilmac12312** [comment]
I feel the hosting option would be quite nice as many of us are tired of seeing the plain enjin or expensive Xenforo and would be wanting an alternative of something in-between

**Comment by Root3287** [comment]
@Lilmac12312 I think a hosting option will be also too exspensive. Some one would have to buy servers like 1-5 servers. Linked together like google and youtube or something like that. That is a nice idea though.

**Comment by Lilmac12312** [comment]
@Root3287 Not if there is some sort of sponsorship given to @samerton such as BeastNode or MCProHosting. I'm not exactly sure how Enjin hosts their websites but I'm quite sure they would re-buy webhosting for a cheap price then earn extra to keep funding their project.

**Comment by Root3287** [comment]
@Lilmac12312 True.

**Comment by Lilmac12312** [comment]
@samerton Any idea on when the next update will be? Can't wait for some new features :)

**Comment by samerton** [comment]
There'll be a bugfix release shortly, however there probably won't be a release with new features for a few days at least.

**Comment by samerton** [comment]
As the questions have been answered, I'll close this issue.
