### ISSUE TITLE
Redirection to the wrong page

### ISSUE THREAD

**Issue by Root3287** [samerton/NamelessMC#24]
Sam, Can you fix this bug where some one would put the software inside of another folder so like a subdomain(Homefile: htadocs/NMC/index.php). Then run the file it will try to go to htadocs/install. Instead of htadocs/NMC/install. On my localhost it going to 127.0.0.1/install. Then the whole system is messed up.

**Comment by Root3287** [comment]
I recremend using define(path, '../'); in every page

**Comment by Root3287** [comment]
Or how else you will fix that because it is also happening to me

**Comment by samerton** [comment]
The system is meant to be a standalone package, therefore it will not work if installed in a sub-directory. Sorry, but this will take quite some time to change.

**Comment by Root3287** [comment]
kk Thanks
