### ISSUE TITLE
New registered username issues? 

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#25]
Not sure what happened but this shows up and it's quite weird.. http://prntscr.com/72h74o

Although when you click on the username it takes you to the users page without any issues.

**Comment by samerton** [comment]
Should be fixed when 0.3.1 is released. I think this is due to the same issue as #21.

**Comment by samerton** [comment]
With the release of 0.3.1, this issue should no longer occur; if not, I'll reopen this.
