### ISSUE TITLE
Last seen & add-on

### ISSUE THREAD

**Issue by Lilmac12312** [samerton/NamelessMC#27]
It would be neat to have a "last seen" somewhere on the users profile showing what server they were last on and how long ago.

Also maybe add in the time the user registered on the forums within this part: http://prntscr.com/738baf

**Comment by samerton** [comment]
Thanks, added the time registered in https://github.com/samerton/NamelessMC/commit/e6c63ac46d16d5b62408c64407c1d35758ca5d97 .

Last seen will come with the ingame statistics integration, as there isn't currently a way of seeing when they were last online.

**Comment by dwilson390** [comment]
Appreciate this is an old request however,  I believe @Lilmac12312 is intending the last seen feature refers to the time last seen on the website, not the server.

**Comment by samerton** [comment]
That should be easy enough to add; when the user was last online on the website is now tracked (for the online users module), this just needs to be displayed on profiles.

**Comment by dwilson390** [comment]
You're such a speedy developer!  Perfect!  :)

**Comment by samerton** [comment]
Added last online in [this commit](https://github.com/NamelessMC/Nameless/commit/889936a12bb0065aa591920702e37a2b7bbb0957) in the new repo.
