### ISSUE TITLE
Add Team section

### ISSUE THREAD

**Issue by TraicionCraft** [samerton/NamelessMC#28]
Add a menu where you can see all the teams and to create a team. In addition to the teams look at the profiles of users.

**Comment by Lilmac12312** [comment]
You may need to elaborate on this. I think you mean Factions instead of "teams". You can do /f list to display all the current made factions on the server

**Comment by samerton** [comment]
Would this require a custom plugin for the Minecraft server?

**Comment by TraicionCraft** [comment]
Does not require exactly a plugin. Users can create their teams on the site and view statistics of team (all deaths and killings of all members)

**Comment by Root3287** [comment]
Well yes you need a plugin or a custom plugin to track the kills and stats. All of that has to be stored on a database. Which is transfer via Plugin

**Comment by Lilmac12312** [comment]
Well if you're going to track kills, deaths and many more then of course you'll be needing a plugin, it's not like the website can handle all that by itself although that would be neat if it could.

He basically wants something like MCPvP as how they allow you to create clans in-game or via the website and invite players to your clan, upload a description of the clan etc

**Comment by Root3287** [comment]
So like an API on the plugin that also can be shared to a site API like Pogostick29Dev is making with the ban-management(Which is a custom plugin(https://www.youtube.com/playlist?list=PLAF3anQEEkzRqU3VCsge3vrciSaQui6OZ)). Is that right @Lilmac12312

**Comment by samerton** [comment]
There's a statistics plugin nearly ready which will be released shortly. The team side of things can be handled web-side, so I can definitely get this implemented in a future release. The issue with this is teams would not be viewable ingame.

**Comment by Lilmac12312** [comment]
@Root3287 yes something like that. 

@samerton Could you not pull information via a HTML webpage to players in-game via MySQL or something? I know it's possible as that's what I used to do to check players and their profile when they logged in(made checks seeing if they were banned, tempbanned etc)

**Comment by samerton** [comment]
@Lilmac12312 As this would require a custom plugin, it's unlikely that this will happen as I don't know Java at this point.

**Comment by Lilmac12312** [comment]
@samerton Someone may be willing to do so for you.

**Comment by Root3287** [comment]
Ill do it if you want me to, but the site needs a custom table and functions.

**Comment by samerton** [comment]
@Root3287 It'd just be the server plugin which is required, I can handle the web-side of things.

**Comment by Root3287** [comment]
We'll or I'll do!

**Comment by samerton** [comment]
Unfortunately as this is requires a custom non-Nameless plugin to actually have the teams ingame, this is slightly outside of the scope of Nameless itself.
If a plugin to manage teams ingame is made, it will be possible to develop a module for Nameless v2 to integrated it with the website ([link to v1/v2 repo](https://github.com/NamelessMC/Nameless)).
