### ISSUE TITLE
Way to remove the "more" tab and add the Staff applications on the nav bar?

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#32]
Is there any way for that?

**Comment by samerton** [comment]
Try replacing the contents of your inc/templates/navbar.php with [this code](https://gist.githubusercontent.com/samerton/0f2b64142d20b1022f4d/raw/23c45a191d00d296a1e0151441763ceac3b3e50b/navbar.php). It is untested, so please back up your inc/templates/navbar.php file before doing so.

**Comment by Kyle1264x** [comment]
Worked flawlessly, thanks, 

Quick question, is there a way to mass email currently?

**Comment by samerton** [comment]
Not at the moment I'm afraid, something I'll add once I change the way emails work.

**Comment by Kyle1264x** [comment]
Appreciate it, Mind messaging me when you need testing for the litebans plugin?

**Comment by samerton** [comment]
Sure, I'll let you know once it's ready.
