### ISSUE TITLE
Litebans

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#33]
http://www.spigotmc.org/conversations/litebans-integration.49689/

Move this here, for email notifications

**Comment by samerton** [comment]
I'll move over my reply to here.

You'll need to replace all contents of the file, so your final file will look something like [this](https://gist.githubusercontent.com/samerton/e0e9538676f7c8e406a4/raw/a49973d12144cb8420d09449fa162aacb0f8624d/ext_conf)

**Comment by Kyle1264x** [comment]
As for the nav bar, should it show up? Because you gave me a changed nav bar code.

Kyle

**Comment by samerton** [comment]
The Infractions link can be found in the bottom-right of the page, next to the copyright notice. You'll need to enable it in the Pages section of the admin panel first though. Would you like a modified navbar which includes the Infractions link up there, instead of in the footer?

**Comment by Kyle1264x** [comment]
Nah. That's fine. Leme get to school and I'll add the code 
Kyle

**Comment by Kyle1264x** [comment]
Testing now

**Comment by Kyle1264x** [comment]
Added the code, Infractions page does work. 
But it seems as if its only registering the "who the staff is" if theyre opp'd or console.
http://prntscr.com/7ac6ps

**Comment by Kyle1264x** [comment]
Also for the overview in the mod cp, you should have it show like
Applications: #

> > Denied
> > Open
> > Accepted
> > Reports:#

**Comment by samerton** [comment]
I think the missing staff members are caused by the package being unable to query Mojang's servers to get the username from their UUID. This won't happen if they've already registered on the website, however I'll look into it.

As for the ModCP overview, I'll add that.

**Comment by Kyle1264x** [comment]
All my staff have registered on my website, Ive made sure of that.

**Comment by Kyle1264x** [comment]
And the few that havent i've registered them for them. It also looks like theyre switched around, Some of my staff are getting kicked instead of doing the kicking. and such

**Comment by samerton** [comment]
Strange, I'll continue to look into it.

**Comment by Kyle1264x** [comment]
Sounds good 

Kyle

**Comment by samerton** [comment]
Can you try the following:

Replace the code of pages/infractions.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/0f2f1425399ee913dc16a03f79e28c97f7be860d/pages/infractions.php)
Replace the code of inc/classes/Infractions.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/0f2f1425399ee913dc16a03f79e28c97f7be860d/inc/classes/Infractions.php)

**Comment by Kyle1264x** [comment]
http://apexnetwork.org/infractions/

Looks like that fixed it, I'll continue looking for bugs

**Comment by samerton** [comment]
The pagination on that page seems pretty broken, I'll fix that now.

**Comment by Kyle1264x** [comment]
I just banned myself 
http://prntscr.com/7adu01
says im unbanned when im banned

**Comment by samerton** [comment]
Can you replace the contents of inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/e41536bcf8bdbfeeef26/raw/60d18847cf25949ee62cf793f49c1d1a97c5b7ae/Infractions.php) for debugging purposes; it doesn't contain any fixes.

**Comment by Kyle1264x** [comment]
http://prntscr.com/7adx0h
http://prntscr.com/7adx61

**Comment by Kyle1264x** [comment]
http://prntscr.com/7adxhl

**Comment by Kyle1264x** [comment]
My staff found a bug on the website 
If they're in the moderator group their picture of their head doesn't load 

Kyle

**Comment by samerton** [comment]
Can you replace the contents of:

inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/d2b5bf3fca2add29de6a/raw/ed9bde542e0f2fa7dfbfafb55e25f7241ee287b7/Infractions.php)
pages/infractions.php with [this code](https://gist.githubusercontent.com/samerton/d2b5bf3fca2add29de6a/raw/764c9b08e8133ad44b3f3bbb6c543126fa7c3b8b/infractions.php)

**Comment by samerton** [comment]
Can't reproduce the issue with your moderator heads missing. Can you temporarily enable custom displaynames (at the bottom of the "General Settings" AdminCP tab), navigate to the Users tab in the AdminCP, edit a user whose avatar isn't working, and check their "Minecraft Username" field is filled in.

**Comment by Kyle1264x** [comment]
Just replaced the contents, same problem as before, Marking them as unbanned when their banned. Just tested on an online user and they also tried to join back
http://prntscr.com/7aelld
http://prntscr.com/7aely5

**Comment by Kyle1264x** [comment]
Just tested with the username thing, whenever theyre put into the Moderator group it removes their name it seems. And it sets as their display name

**Comment by Kyle1264x** [comment]
All bans are an issue, someone was just temp banned,
http://prntscr.com/7aephf
same issue, should be a week

**Comment by samerton** [comment]
The debug code I sent you earlier showed that your database value is different to mine; how recent is your LiteBans version?

**Comment by Kyle1264x** [comment]
the most recent version

**Comment by Kyle1264x** [comment]
Just re-updated the plugin, i'll try now

**Comment by Kyle1264x** [comment]
Still showing as unbanned

**Comment by samerton** [comment]
The problem is your database value for "active" seems to be empty, whereas it should be either 0 or 1. I'll send some more code over soon.

**Comment by Kyle1264x** [comment]
Here are the tables in my database http://prntscr.com/7aesmd

**Comment by samerton** [comment]
Can you replace the contents of your inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/2e90189bad3b1da89ae8/raw/00488da4d189b0ccb2c168328c012622ce821188/Infractions.php)

**Comment by Kyle1264x** [comment]
http://prntscr.com/7aey2w

**Comment by Kyle1264x** [comment]
Would you like my database for this? I can download it off phpmyadmin or send you snippets

**Comment by samerton** [comment]
Could you take a screenshot of the bans table within your database?

**Comment by Kyle1264x** [comment]
here are the most recent bans:
http://prntscr.com/7aeyxt

heres the bar:
http://prntscr.com/7aez2p

**Comment by samerton** [comment]
The issue here seems to be with the database values; your "active" values are set as 0 when they should be 1, which means they're set as unbanned.

**Comment by Kyle1264x** [comment]
They are banned though. Like if they try to join in, it says theyre banned
http://prntscr.com/7af416
http://prntscr.com/7af462
http://prntscr.com/7af49y

**Comment by Kyle1264x** [comment]
If i need to i can just flush my database

**Comment by samerton** [comment]
Can you replace the contents of:

inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/314c611ebea936a58e95/raw/3aeb683885cb07dcd1f8747ee44e3e7aff9874f4/Infractions.php)
pages/infractions.php with [this code](https://gist.githubusercontent.com/samerton/829ac9af50999339a3a9/raw/320ab6cabf6288961caf87939af0d5529f76a117/infractions.php)

**Comment by Kyle1264x** [comment]
Im guessing debugging?

**Comment by Kyle1264x** [comment]
http://prntscr.com/7af6ft

Banned two people permanently

**Comment by Kyle1264x** [comment]
http://prntscr.com/7af6ro from the table

**Comment by samerton** [comment]
Interestingly, the database shows an active value as "1" whereas the query isn't picking up any value at all. Can you navigate to the Bans table "structure" tab in phpMyAdmin and let me know what the "type" is set to for the "active" column?

**Comment by Kyle1264x** [comment]
http://prntscr.com/7afams

**Comment by samerton** [comment]
Can you replace the contents of:

inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/2b58a45747f7f9f86c7d/raw/4a86abb4eedbc70dfbc6a2b4e19d06574ea04a89/Infractions.php)
pages/infractions.php with [this code](https://gist.githubusercontent.com/samerton/2b58a45747f7f9f86c7d/raw/aeca523ef22e23d485a01862a52de0482c2a7a46/infractions.php)

**Comment by Kyle1264x** [comment]
Added, what would you like from those?

**Comment by samerton** [comment]
Wondering if that would have fixed the issue, however I think I may know what's happening. The problem is, the querying library in the package doesn't support the database query I'll need. I'll keep working on it though.

**Comment by Kyle1264x** [comment]
Got it, just let me know if you need me to do anything

**Comment by Kyle1264x** [comment]
If you need me to, i can drop the database and start from a clean slate

**Comment by samerton** [comment]
One last test before reworking the queries. Could you replace the contents of:

inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/92c0a0aa30ba03f06d31/raw/1eb75871fe3dfc7b41c6f094e959b18e86451417/Infractions.php)
pages/infractions.php with [this code](https://gist.githubusercontent.com/samerton/92c0a0aa30ba03f06d31/raw/464f54a4b6a0a1c4176363a75560a34eda9a2f31/infractions.php)

**Comment by Kyle1264x** [comment]
http://prntscr.com/7afh5f
did not work

**Comment by samerton** [comment]
Can you replace the contents of inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/0bd953039829c79fe9ee/raw/e57f950148d3d414ffbcb515cdc0d6691c97e82b/Infractions.php).

Strangely, I can't reproduce the error on my local server.

**Comment by Kyle1264x** [comment]
http://apexnetwork.org/infractions/
No idea what this means lol

**Comment by samerton** [comment]
Seems to have worked, it's converted the bit field type to a usable value.

Can you replace the contents of:

inc/classes/Infractions.php with [this code](https://gist.githubusercontent.com/samerton/8efff6786794dcb3de2d/raw/3c205e29d988150a4769fa06247f6031e967eb39/Infractions.php)
pages/infractions.php with [this code](https://gist.githubusercontent.com/samerton/8efff6786794dcb3de2d/raw/21a825dac40bfcd3debbedfa82df37678483c3e6/infractions.php)

**Comment by Kyle1264x** [comment]
Seems like that worked as well

**Comment by Kyle1264x** [comment]
http://apexnetwork.org/infractions/

**Comment by samerton** [comment]
Also fixed the issue you're having with moderators heads missing; can you replace the contents of pages/admin/users.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/0615fd9ec52b946168c784b2a7f77fdc2e2ec40a/pages/admin/users.php)

**Comment by samerton** [comment]
Forgot to add, you'll also need to head into the Admin panel's Users tab, select a user whose avatar is missing, and then click Submit.

**Comment by Kyle1264x** [comment]
Awesome thanks man, i'll post back with any mrore bugs
