### ISSUE TITLE
Internal error while installing.

### ISSUE THREAD

**Issue by Foorack** [samerton/NamelessMC#34]
_Chrome Website Data_
General:

> Request URL:http://XXX.XXX.XXX.XXX/install/?step=settings
> Request Method:POST
> Status Code:500 Internal Server Error

Response Headers:

> Content-Type:text/html; charset=UTF-8
> Date:Thu, 28 May 2015 20:17:52 GMT
> Expires:Thu, 19 Nov 1981 08:52:00 GMT
> Pragma:no-cache
> Server:Apache/2.4.6 (CentOS) PHP/5.5.25
> X-Powered-By:PHP/5.5.25

Query String Parameters:

> step:settings

Form data:

> Site_name:XXXXXXXX
> outgoing_email:noreply@XXXXXXX.XXXXXXX
> youtube_url:
> twitter_url:https://twitter.com/SSSSSSSSSS
> twitter_feed:01010101010101010101010
> gplus_url:
> fb_url:
> user_usernames:0
> user_avatars:0
> user_avatars:1
> page_stats:0
> page_donate:0
> page_donate:1
> page_vote:0
> page_vote:1
> page_infractions:0
> page_infractions:1
> page_staff_app:0

Nothing in the apache logs.

I also tried setting error_reporting to "-1" as that would report everything and 'display_errrors' to 1 however this did not change anything. Still seeing no errors print.

**Comment by Foorack** [comment]
Hold on, I'm writing. Pressed enter by mistake.

**Comment by samerton** [comment]
Can you check the logs within /var/log?
If there's nothing there, could you add [these lines of code](https://gist.githubusercontent.com/samerton/4909c7694ff435280765/raw/e2d5e7e7ea131e271ca28975def2dc082230cbaf/Error%20Reporting) into pages/install.php, underneath the opening <?php tag, in case we can get an error appearing on the installer.

Not sure what could be causing this, unfortunately I'd need some sort of error log to make anything out of it.

Edit: Just seen the updated post, I'll try and figure it out from the HTML snippet.

**Comment by Foorack** [comment]
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /var/www/namelessmc/pages/install.php:348 Stack trace: #0 /var/www/namelessmc/pages/install.php(348): DateTime->__construct() #1 /var/www/namelessmc/index.php(157): require('/var/www/namele...') #2 {main} thrown in /var/www/namelessmc/pages/install.php on line 348

**Comment by samerton** [comment]
I see what's happening, I'll push a fix now.

**Comment by Foorack** [comment]
Ok, thanks. :smiley:

**Comment by samerton** [comment]
Can you replace the contents of your index.php file in the root directory with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/master/index.php). It's just a quick and temporary fix, but it's untested.

**Comment by samerton** [comment]
I believe this issue has been resolved, closing now
