### ISSUE TITLE
Way to change the admin email?

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#35]
How can i change the email that it sends the activation email from?

**Comment by samerton** [comment]
There's not a field for it yet in the AdminCP, I can quickly add one now though.

**Comment by Kyle1264x** [comment]
That sounds good man, Appreciate it.

**Comment by Kyle1264x** [comment]
Also the donate page, is there anyway to put the HTML version of buycraft in

**Comment by samerton** [comment]
Added the outgoing email field in the [latest commit](https://github.com/samerton/NamelessMC/commit/18444c09cd7b4bfd4ca3c73c9345bbae8ad66bb7). If you want to install this update before the next pre-release, replace the contents of pages/admin/general.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/master/pages/admin/general.php).

As for the donate page, you'll need to edit the pages/donate.php file manually and add an iFrame. If you replace the contents of pages/donate.php with [this code](https://gist.githubusercontent.com/samerton/e146aa83aa6f51f13b2d/raw/c52a9bfe49d354ecfebb2901c94634fdaed9f0b0/donate.php), it should do it for you.
