### ISSUE TITLE
Way to allow certain groups to accept/deny applications

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#36]
anyway to do this?

**Comment by samerton** [comment]
Not currently I'm afraid, only moderators or administrators. I'll add it to the to-do list.

**Comment by Kyle1264x** [comment]
The only issue is i dont want to give the admin CP to people. Whatever, looking forward to seeing this

**Comment by samerton** [comment]
If they're in the Moderator group, you can give them access via the ModCP (this is an option within the Staff Applications tab of the AdminCP).

Edit: sorry, just noticed the issue referred to accepting/denying applications.

**Comment by Kyle1264x** [comment]
They are in the moderator group, but they cannot accept/deny

**Comment by samerton** [comment]
Added an option to allow moderators to accept/reject applications in the [latest commit](https://github.com/samerton/NamelessMC/commit/cabe85ed4ccfd4d391b9c771596c3eb9f22b1eb2), however as this requires database changes I'm afraid you'll have to wait until the next release before using the new features.
