### ISSUE TITLE
'Update UUID' returns empty field for user UUID

### ISSUE THREAD

**Issue by dwilson390** [samerton/NamelessMC#39]
Hi samerton,

When using the 'Update UUID' task under AdminCP -> Users -> (Specific User) -> Update UUID the UUID field becomes empty, subsequently, using the 'Update Name' task will then return a blank field (as there is no UUID to search).

Not a huge issue as you can retrieve the UUID manually anyway however would be nice to see this fixed.

If you busy, I can look into this for you and push a commit if I find anything :)

Thanks for all your work on this amazing software!

**Comment by samerton** [comment]
Hi,

Unfortunately I can't reproduce this issue. The only thing I can think of is that the script was unable to query Mojang's servers.

Is there already a value in the field for their Minecraft username?

**Comment by dwilson390** [comment]
Yeah, there is. In fact I even tried copying the value on the mcname field into https://namemc.com/ and it returned everything as usual. Would this have anything to do with my using HTTPS/CloudFlare?
On 4 Jun 2015 17:19, samerton notifications@github.com wrote:Hi,

Unfortunately I can't reproduce this issue. The only thing I can think of is that the script was unable to query Mojang's servers.

Is there already a value in the field for their Minecraft username?

**Comment by samerton** [comment]
Having HTTPS and Cloudflare enabled shouldn't matter; seems to work fine on the demo which uses Cloudflare. Very strange, I'll have to continue to look into it.

**Comment by dwilson390** [comment]
Thanks, I'll continue to try and produce this for you too.
On 4 Jun 2015 17:43, samerton notifications@github.com wrote:Having HTTPS and Cloudflare enabled shouldn't matter; seems to work fine on the demo which uses Cloudflare. Very strange, I'll have to continue to look into it.

**Comment by samerton** [comment]
Found and fixed the issue. Thanks for the report.
