### ISSUE TITLE
Regarding the issue with Post titles being removed

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#41]
Which files do we replace to fix this?

**Comment by samerton** [comment]
Hi,

I'll push out an official update soon, but for now you can replace the contents of your pages/forum/edit_post.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/e95778f456582b4b8668b9c58415cc857da2431f/pages/forum/edit_post.php)

**Comment by Kyle1264x** [comment]
Awesome thanks. Will the update contain the way to make it so different groups can accept/deny staff requests?

**Comment by samerton** [comment]
I'm afraid I have to push an emergency update now, I'll get that finished for the next release.

**Comment by samerton** [comment]
I'll close this now, the ability to allow certain groups to view/accept/deny applications will be included in the next release.

**Comment by Kyle1264x** [comment]
Eta on the release?

Kyle

**Comment by samerton** [comment]
Should be within the next couple of weeks, however it's still exam period over here so I'll make a start after they've finished.
