### ISSUE TITLE
Make forum tab look smoother?

### ISSUE THREAD

**Issue by zRiaz** [samerton/NamelessMC#43]
Personally, I think that each parent should have a little gap between them (small one) to show a little seperation.

Also the border around the forum tabs are currently rectangular, and I think that if the corners had like circuler edges it would look a look better..

Also the Stats part on the forum tab looks like this:
http://gyazo.com/31d20a435f643062708ab6132b5e2805
I think that if it was just slightly extended, it could fit up the total and topic/post thing on the same line to save up some space. This would also mean that the bar underneath the forum categories (this one: http://gyazo.com/6fe1c11b584ea0a89664eb4f71481ee7) Which is mostly just a empty white box.. Could be removed to make the forum page not take up too much space. (when I say removed, I mean the parts of it that isnt being used)

Same thing about the "Last Post" section, it could be a bit wider and save up some more space on the site.

Thats my few suggestions :3 Wrote it in sort of a hurry, so if any questions. Feel free to ask.

**Comment by samerton** [comment]
Changing the forum table view is something I've been meaning to do, I'll look into it for version 1.0. Thanks for the suggestion.

**Comment by samerton** [comment]
The forum table view can now be changed with custom templates/themes; I'll go ahead and mark this issue as closed now.
