### ISSUE TITLE
Error while registration

### ISSUE THREAD

**Issue by Foorack** [samerton/NamelessMC#44]
Notice: Undefined variable: validation in /var/www/namelessmc/pages/register.php on line 189

Fatal error: Call to a member function passed() on a non-object in /var/www/namelessmc/pages/register.php on line 189

**Comment by samerton** [comment]
Does this happen upon opening the registration page for the first time, or after you've submitted the form?

**Comment by Foorack** [comment]
After submission...

**Comment by samerton** [comment]
Can't reproduce any issues, but can you try replacing the contents of pages/register.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/master/pages/register.php)?

**Comment by Foorack** [comment]
I did,
"There was a problem creating an account."

**Comment by samerton** [comment]
Can you head into the AdminCP, and see if there is an update available?

**Comment by Foorack** [comment]
Updated.

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uuid' cannot be null

**Comment by samerton** [comment]
Can you try replacing the code of inc/integration/uuid.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/28d01d2c9fd7e327d5e3093bea63d49fe6ffe9d4/inc/integration/uuid.php)?

**Comment by Foorack** [comment]
It worked!! :D thx

**Comment by samerton** [comment]
No problem, glad it worked
