### ISSUE TITLE
Error when registering

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#45]
http://prntscr.com/7lufkf

**Comment by samerton** [comment]
Can you head into the AdminCP and check if there is an update available? I believe this error was fixed in [version 0.3.3](https://github.com/samerton/NamelessMC/releases/tag/v0.3.3)

**Comment by Kyle1264x** [comment]
Says i am up to date

**Comment by samerton** [comment]
Can you manually replace the contents of your inc/classes/DB.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/master/inc/classes/DB.php)?

**Comment by Kyle1264x** [comment]
it says SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uuid' cannot be null

even after replacing code

**Comment by samerton** [comment]
Can you replace the contents of inc/integration/uuid.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/28d01d2c9fd7e327d5e3093bea63d49fe6ffe9d4/inc/integration/uuid.php)? If it still doesn't work, I should be able to push a new fix later.

**Comment by Kyle1264x** [comment]
didnt work

**Comment by samerton** [comment]
This should fix it for now. Can you replace the contents of pages/register.php with [this code](https://github.com/samerton/NamelessMC/raw/a95588c0bed27a185538f3877529fcf13d505fc0/pages/register.php)
