### ISSUE TITLE
Will NamelessMC support multi-language in the future?

### ISSUE THREAD

**Issue by XavierWang3P** [samerton/NamelessMC#47]
Hi,I'm from China.I use NamelessMC on my server,but some guys couldn't see the English any more!And Google Website Translate is useless!I hope NamelessMC will support multi-language.I can also make the Simplified Chinese and Traditional Chinese package.
Have a good day!   : )

**Comment by samerton** [comment]
Hi there,

Multi language support will be included in version 1.0, which should be released at some point next month.

Thanks,
Sam.

**Comment by XavierWang3P** [comment]
Copied that. Thank you! :-)

**Comment by samerton** [comment]
Multi language support is included in the latest 1.0 development builds, however it's recommended you don't upgrade yet as it's still in testing stages. The new repository can be found [here](https://github.com/NamelessMC/Nameless).
