### ISSUE TITLE
Verification Email

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#48]
People arent getting it, or it goes right to spam. How can i fix this?

**Comment by samerton** [comment]
If the email is being sent, but it's going into the Spam folder, not much can be done. However, this does show that the email function works.

If the email is not being sent at all, this should be fixed in the upcoming version 1.0 which includes a new email library.

**Comment by Kyle1264x** [comment]
Okay, sounds good. Can you make it login to a gmail account, so it uses googles' api to send? so its not considered spam

**Comment by samerton** [comment]
To add onto my previous reply, if you replace the code of pages/admin/user.php with [this code](https://raw.githubusercontent.com/samerton/NamelessMC/master/pages/admin/users.php), you can manually activate a user's account by editing their user in the AdminCP and clicking "Validate User".

Yes, the upcoming mail library included in version 1.0 will have the ability to use gmail to send emails.

**Comment by Kyle1264x** [comment]
Sounds good, Thanks man

**Comment by samerton** [comment]
Fixed in the latest 1.0 development, found [here](https://github.com/NamelessMC/Nameless)
