### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by zRiaz** [samerton/NamelessMC#49]
Hello.

Is there a ETA Date or exact date for the 1.0 release?
(I really look forward for the email improvements and would need them asap)

**Comment by samerton** [comment]
Hi,

I'm afraid I can't give an exact date as there's still quite a lot to do, however I'd expect it to be ready in the second half of the month. I'll keep you updated and let you know as soon as I can give you a date.

**Comment by zRiaz** [comment]
Even if the 1.0 update is far away, could you please prioritise and put out the fix for the email system before 1.0 release. Im in big needs of it by fridayish.

Thank you.

**Comment by samerton** [comment]
I'll see what I can do.

**Comment by Kyle1264x** [comment]
Just looking for an ETA on the 1.0

**Comment by samerton** [comment]
The latest 1.0 development builds are now out, however it's still in testing stages. The repository can be found [here](https://github.com/NamelessMC/Nameless).
