### ISSUE TITLE
Unban user

### ISSUE THREAD

**Issue by Kyle1264x** [samerton/NamelessMC#50]
Anyway to see current forum bans? and to unban them?

**Comment by samerton** [comment]
These are features I've actually overlooked, I'll get them added for version 1.0.

**Comment by Kyle1264x** [comment]
Thanks, is there an ETA for 1.0?

**Comment by samerton** [comment]
Unfortunately, as there's a long way to go, I can only say I'd expect it to be ready in the second half of this month.

**Comment by samerton** [comment]
Added in the latest 1.0 development builds, found [here](https://github.com/NamelessMC/Nameless).
