### ISSUE TITLE
Voting links don't go where they're supposed to.

### ISSUE THREAD

**Issue by ImKanga** [samerton/NamelessMC#55]
When I click a voting link, instead of taking me to, planetminecraft.com it will take me to http://ausconetwork.com/vote/www.planetminecraft.com/. I believe this is a bug, although I could be wrong :) 

By the way, How close are we towards seeing version 1.0?

Thanks,
- Kanga

**Comment by samerton** [comment]
Hi,

Can you prefix the vote link you've specified with "http://"? I'll add a check to do this automatically for version 1.0, which should be released within the next couple of weeks.

Thanks,
Sam.

**Comment by ImKanga** [comment]
Alright, tried it and it works! Thanks so much. One more thing, groups with custom permission? I understand you can make groups with labels but groups with their own permissions. Is this possible yet?

Thanks,
- Kanga

**Comment by samerton** [comment]
Custom permissions are very basic at the moment, and they're restricted to basic forum permissions. These can be configured in the AdminCP's forum page upon editing a forum.

There will be more permissions available following the release of 1.0, possibly in 1.1.

Thanks,
Sam.

**Comment by ImKanga** [comment]
Sorry this is going offtopic. But one more thing, I cant't query my server. I use the external query and it works but not the internal one. I believe the internal server query code is Dinnerbone's? I used his website which has the server tracker. It comes up fine. My IP is - play.ausconetwork.com, I have also put the port on the end of that. Still doesnt work. Not sure what else I could do to fix this..

Thanks,
- Kanga

**Comment by samerton** [comment]
Unfortunately I haven't added a way of viewing the query error just yet, hopefully this will be included in 1.0. The library used is [this one](https://github.com/xPaw/PHP-Minecraft-Query); the issues there may offer a solution.

The only thing I'm aware of at the moment is that some web hosts block fsockopen, which could be the issue here.

Thanks,
Sam.

**Comment by ImKanga** [comment]
Ahh ok. Thanks so much for quick response and great response! I will enquiry about the web hosting idea.

Thanks,
- Kanga

**Comment by samerton** [comment]
No problem, I'll go ahead and close the issue now.

Thanks,
Sam.
