### ISSUE TITLE
Prioritied things to do.

### ISSUE THREAD

**Issue by zRiaz** [samerton/NamelessMC#56]
1: Add the EMail Fix.
2: Make it so we can add custom tabs, or make it so we can just itegrate the Donation Store directy instead of just listing the packages because it looks ugly :[ (sry)
3: The Play page, I find it very useful and cool. Especially how I can just display the servers on Bungee and the amount of people on each! But, a seperate page just for that isnt needed. Maybe make it display on the side of the screen constantly on every page? (Or something)
4: Divide up the Forum categories. Should definetly be a space between each parent node. To indicate seperation of topics.
5: It now says "More" and when I click more its just Staff Applications. I mean there is still a lot of space on the like category bar thing so it should just display the Staff Applications tab too.
6: Staff Apps, after reading the application you should no longer get a notification about it.
It shouldn't require you to accept/deny them to get the notification gone. Seeing them should be enough.

This is basically some things I had on the top of my mind that I find very useful/essential to using Nameless, hope to see most of it added shortly.

**Comment by samerton** [comment]
1. I apologise for not including this already, however it's quite complex. Hopefully I can release a fix before too long.
2. Version 1.0 will allow for a custom template for the "Donate" page, and also for the direct embedding of a donation store.
3. Sure, I'll add a module for version 1.0 which includes the server status on every page.
4. I'm hoping to add this for 1.0, if not it'll be in 1.1.
5. Hopefully this will be customisable in 1.0.
6. I'll try and include this for 1.0.

Thanks for the suggestions.

**Comment by Lilmac12312** [comment]
Auto updating would be neat too.

**Comment by samerton** [comment]
I don't think auto updating will ever be implemented, however a system such as the one used by IPBoard or XenForo may be, where the update download file only contains the files you need to replace, so there's no picking out files yourself.

**Comment by samerton** [comment]
A little update with the first 1.0 builds becoming available:
1. Included in the latest [1.0 development builds](https://github.com/NamelessMC/Nameless).
2. Donation stores can be embedded in the new development builds.
3. Still working on this.
4. Coming in version 1.1.
5. Will be customisable before the full 1.0 release.
6. Will come when staff applications for 1.0 are finished.

**Comment by samerton** [comment]
Update with the remaining points:

3 - Hopefully coming as a v2 widget.
6 - Coming in the new v2 rewritten application module.

You can find the v2 repo [here](https://github.com/NamelessMC/Nameless/tree/v2).

I'll go ahead and mark this as closed.
