### ISSUE TITLE
*Suggestion* Add Markup to Text Editor

### ISSUE THREAD

**Issue by imperiagroup** [samerton/NamelessMC#57]
I think a lot of people would like to see Markup added in the text editor for the forums. Lots of communities could find this of use, especially ones that are very code oriented and would like to make their posts look better. Just a suggestion.

Motorbond

**Comment by samerton** [comment]
Hi,

I'll create a poll at some point to decide on this, as we'd be unable to include both Markup and the current WYSIWYG editor. I'll let you know when I've created the poll.

**Comment by imperiagroup** [comment]
Sounds good. Thanks.

**Comment by samerton** [comment]
An option to switch between HTML + Markdown is in [v2](https://github.com/NamelessMC/Nameless/tree/v2).
