### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by ghost** [samerton/NamelessMC#60]
1. Ability to add custom pages
   i. Redirection to URL
   ii. HTML script (might not be safe though..)
2. Text feature for staff application
   i. A text box for the staff application for why I should be staff, etc, etc
3. Chat support
   i. Use API (mcjsonapi is an option) to get last 50ish chat messages and put them in a chatbox where the user cannot say anything. Sort of like a scrollable "html-ized" log of chat.
4. Polls
   i. This can be forums (where topic starter can create)
   ii. This can be on the "portal" site where moderators and admins can create the polls while logged        in users can vote

**Comment by samerton** [comment]
Hi,

1: Custom pages are half-implemented already, and will be fully ready for version 1.0 in the next couple of weeks. They'll only include text formatting (same editor as posts), however custom HTML could be added in the future.

2: This is already possible, you can select the question type as "Text Area".

3: This is a possibility for the future, I'll look into it.

4: Polls are planned, however they won't be included in the next couple of releases.

Thanks for the suggestions.

**Comment by ghost** [comment]
Ah thanks

**Comment by samerton** [comment]
I'll give a final update on these so I can mark this as closed, seeing as we have a [different repo](https://github.com/NamelessMC/Nameless) for v1/v2.

1 - Redirect links added in v1, full HTML scripts coming in v2
3 - Can be added as a custom v2 module, once v2 is fully released
4 - Planned for an addition after v2, possibly v2.1
