### ISSUE TITLE
Cannot Create Admin User

### ISSUE THREAD

**Issue by ghost** [samerton/NamelessMC#63]
When I try to create the admin user it says "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 1"

The data I'm entering is

Username: Genocidal
Minecraft Username: Genocidal
Email: *************_@gmail.com (censored but same character length)
Password: ***_******\* (11 characters)

**Comment by ghost** [comment]
this only happens on my dedicated server running ubuntu 15.04. on my windows home pc it works fine without those errors.

**Comment by samerton** [comment]
Fixed in 96eb820f959cb2b86d4533f3e4b1762b13bade9c, also reported in the [support thread](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/).
