### ISSUE TITLE
Registering with non valid Minecraft Username

### ISSUE THREAD

**Issue by Bob1nz** [samerton/NamelessMC#64]
Is there a plan to add a check that a Minecraft Username is valid?
I was able to register using a non valid name which results in the user not being able to access their profile as the Column 'uuid' cannot be null.

**Comment by samerton** [comment]
Unable to reproduce this issue, currently all usernames must be valid Minecraft accounts; if not, the registration won't be successful. How were you able to register using a non valid name?

**Comment by Bob1nz** [comment]
I was able to register with the username "harry potter" It created the account and obviously could not get the uuid.
I will try it again and see if I can provide some more information.

**Comment by Bob1nz** [comment]
I have made a short clip showing what I did to register with a non valid name.
https://drive.google.com/file/d/0ByxnSCB19PNlV09EVi1mTERwRDQ/view?usp=sharing

**Comment by samerton** [comment]
I'm able to reproduce now, the issue seems to occur when there's a space in the username. Pushing a fix now.
