### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by mcreef** [samerton/NamelessMC#65]
Hey,
when i Clone the GIT Repo to my Webserver, it says me:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by samerton** [comment]
Can you check your "/var/log/apache2/error.log" file for errors?

**Comment by mcreef** [comment]
My Log file:

[Mon Sep 07 08:57:35 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.41-0+deb7u1 configured -- resuming normal operations
[Mon Sep 07 08:57:48 2015] [alert] [client 84.130.109.101] /var/www/NamelessMC/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
[Mon Sep 07 08:57:55 2015] [alert] [client 84.130.109.101] /var/www/NamelessMC/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

**Comment by samerton** [comment]
Try the following command in your terminal (Ubuntu):

sudo a2enmod rewrite && sudo service apache2 restart

**Comment by mcreef** [comment]
Now, it says : 404 Not Found

**Comment by samerton** [comment]
Can you ensure that you have moved all files from the download directly into your website's root directory, and that there is a directory entitled "pages" also within the root folder, containing a file named "install.php".

**Comment by mcreef** [comment]
OKay now it works! Can i disable the Forum section?

**Comment by samerton** [comment]
Not currently; the news section on the homepage relies on the forum section. You can manually remove the news section from "pages/index.php" and remove the navbar link to the forums in "inc/templates/navbar.php", however this will make the homepage look rather empty.

**Comment by mcreef** [comment]
Okay, now is the Problem, when i completed the Installation, and join the WebSite, than comes the Install dialog!

**Comment by samerton** [comment]
Sounds as though the installer was unable to delete itself automatically. You can fix this by deleting pages/install.php manually.

**Comment by mcreef** [comment]
Okay

**Comment by samerton** [comment]
I'll close this issue now it's been resolved.

**Comment by IceRaider** [comment]
I don't have a install.php file

**Comment by CoderFetch** [comment]
@IceRaider 

Hey,
There is a new repository for NamelessMC [here](https://github.com/NamelessMC/Nameless).

**Comment by samerton** [comment]
@IceRaider As @fetch404 says, we have a new repository for version 1.0 development. However, if you'd like to install version 0.4.0 (this repository), simply opening up your website in your browser will take you to the installer. If not, try redownloading the package and trying again.
