### ISSUE TITLE
issue installing. Hosting company said to contact you.

### ISSUE THREAD

**Issue by fenix12585** [samerton/NamelessMC#66]
Hello, I am using godaddy to host my site and I really love everything about this backend. I can not install the sql database settings though. I have tried to follow the steps they have provided... however the connection is always refused. I spoke to a tier 3 technical support rep who specializes in database management and he confirmed that the hosting is working correctly and tried to set up the information for me. Also no luck. He recommended that I reach out to you for assistance. I checked the other issues and did not see anything similar. Can you help? I really want to use this.

The exact error message I am receiving is:
SQLSTATE[HY000] [1045] Access denied for user 'namelessmc'@'localhost' (using password: YES)

**Comment by samerton** [comment]
Unfortunately I can't reproduce your issue, nor can I see a cause.

Can you try installing the latest 1.0 testing release [from here](https://github.com/NamelessMC/Nameless), and see if that helps at all?

**Comment by fenix12585** [comment]
That did work perfectly. It looks great so far! I am having several new errors now, they are showing up after I added a server name in the core section of the admin. This is the errors displaying on my user side.Just to clarify these are from the 1.0 latest download available.Notice: Undefined offset: 0 in /home/thecraftersguild/public_html/tester/pages/index.phpon line 15Notice: Trying to get property of non-object in /home/thecraftersguild/public_html/tester/pages/index.phpon line 15Notice: Undefined offset: 0 in /home/thecraftersguild/public_html/tester/pages/index.phpon line 16Notice: Trying to get property of non-object in /home/thecraftersguild/public_html/tester/pages/index.phpon line 1---- On Tue, 03 Nov 2015 16:59:59 -0500  samertonnotifications@github.com wrote ----Unfortunately I can't reproduce your issue, nor can I see a cause.Can you try installing the latest 1.0 testing release from here, and see if that helps at all?—Reply to this email directly or view it on GitHub.

**Comment by samerton** [comment]
You'll need to head back into your AdminCP's Minecraft tab, and set the "main server" from the dropdown within the "Servers" tab.

**Comment by fenix12585** [comment]
Ahh ok that's not a problem, I updated it and it's working. And final questions :)1) where can I download the server plugin from? What are the advantages of using it? 2) when will you add templates to the themes?3) when do you plan on have the 1.0 release version ready?Thanks again for everything!---- On Tue, 03 Nov 2015 17:28:41 -0500  samertonnotifications@github.com wrote ----You'll need to head back into your AdminCP's Minecraft tab, and set the "main server" from the dropdown within the "Servers" tab.—Reply to this email directly or view it on GitHub.

**Comment by samerton** [comment]
Glad it's working!

1) The plugin's not quite ready yet. It will offer features such as ingame registration and rank synchronisation, and in the future a ticket system will be implemented.
2) Custom templates are already implemented, you can find them in the **styles/templates** folder.
3) Unfortunately I can't really give an estimate due to the unpredictability of university work, however I'd hope to release it before the end of the year.

**Comment by fenix12585** [comment]
That is awesome! Do you k ow when the plugin and ticket system will be ready? This is all very exciting! You really have an amazing platform here. And I understand the university work... A release by the end of the year would be great! Is there something I can subscribe to so that I don't miss any updates?---- On Tue, 03 Nov 2015 17:43:17 -0500  samertonnotifications@github.com wrote ----Glad it's working!1) The plugin's not quite ready yet. It will offer features such as ingame registration and rank synchronisation, and in the future a ticket system will be implemented.2) Custom templates are already implemented, you can find them in the styles/templates folder.3) Unfortunately I can't really give an estimate due to the unpredictability of university work, however I'd hope to release it before the end of the year.—Reply to this email directly or view it on GitHub.

**Comment by samerton** [comment]
The plugin/ticket system will be ready shortly after the 1.0 full release.

To keep up to date with the project, you can either [star the repository on Github](https://github.com/NamelessMC/Nameless), or follow either the [official thread](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/) or [myself](https://www.spigotmc.org/members/samerton.10676/) on Spigot.
