### ISSUE TITLE
Page displays text instead of bootstrap.

### ISSUE THREAD

**Issue by BurritoWrapped** [samerton/NamelessMC#67]
Hey - I'm having trouble installing the software where when I try to load the page, where instead I just get a the page code displayed.

**Comment by BurritoWrapped** [comment]
BUMP

**Comment by TheMeq** [comment]
Does your host support PHP? If not, your server won't know how to process it and display it as plain text

**Comment by samerton** [comment]
Hi,

As @TheMeq says, it sounds as though PHP isn't installed.
If it is, would you be able to send me a link to your site?

**Comment by BurritoWrapped** [comment]
EDIT:
Here: http://error.clashpvp.me:8070/

**Comment by samerton** [comment]
Yup, looks as though PHP isn't installed.
Are you running the website on a dedicated server?

**Comment by BurritoWrapped** [comment]
I'm using a 6GB vps from VPSDime.

**Comment by samerton** [comment]
It looks like you already have Apache on there; try the following commands.

sudo apt-get install php5 libapache2-mod-php5

Once that's done, try the following command:

a2query -m php5

If it says the php5 module is not enabled, simply enable it with

sudo a2enmod php5
sudo service apache2 restart

**Comment by samerton** [comment]
I believe this is an issue with the server configuration and not Nameless itself; I'll close this issue for now.
