### ISSUE TITLE
Problem signing in

### ISSUE THREAD

**Issue by ChanceSD** [samerton/NamelessMC#71]
I followed all the steps to install but when it asks me to re-authenticate in the end, it just doesn't work.
I'm very sure i entered the right username and password but when clicking sign in, just nothing happens, page reloads but doesn't sign me in.

The problem might be i'm using nginx, how do i convert your htaccess file into a nginx config?
Currently i'm using this:

if (!-f $request_filename) {
    rewrite ^(.*)$ /index.php?a=$uri;
}

**Comment by samerton** [comment]
There's an example configuration for nginx in the new version 1.0 repository. Try [this](https://raw.githubusercontent.com/NamelessMC/Nameless/master/nginx.example) and see if it helps.

**Comment by ChanceSD** [comment]
Tried that but still same problem, maybe it's not an issue with nginx.
Guess i will try version 1.0 and see how it works.

**Comment by samerton** [comment]
I've not been able to reproduce this issue at any point, however it may be a new error. Trying 1.0 might be a good idea, hopefully it's not present there.

**Comment by ChanceSD** [comment]
Tried 1.0, got a similar error but this time everything installed fine, the website shows up and everything. 
However, when logging in i get "Invalid token, please try again". Tried going on forgot password but entering my username also gives an error.

**Comment by samerton** [comment]
Would you be able to send me a link to your website?

**Comment by ChanceSD** [comment]
Here: http://kabucraft.servegame.com/

**Comment by samerton** [comment]
Seems as though your web server isn't storing session data for some reason. This could be down to the directory that PHP uses to store session data not being writable.

In order to see whether this is the case you'll need to do the following:
Add the following code to the very bottom of _core/includes/template/navbar.php_:

if (!is_writable(session_save_path())){
    echo '<br />Your session path ' . session_save_path() . ' is not writable.'; 
}

Does an error message appear at the top of your page?

**Comment by ChanceSD** [comment]
Thank you very much! 
That fixed it, it was /var/lib/php which had group set to apache if anyone ever gets the same issue.
