### ISSUE TITLE
Register new users

### ISSUE THREAD

**Issue by ChanceSD** [samerton/NamelessMC#73]
When users try to register, the checkbox (i assume) doesn't show up as you can see here:
http://kabucraft.servegame.com/register/

I tried setting the recaptcha key but didn't help.
Edit: Using Nameless 0.4.0

**Comment by samerton** [comment]
Looks like there's an error which is preventing the end of the page from loading.

Can you add [these lines of code](https://gist.githubusercontent.com/samerton/4909c7694ff435280765/raw/aa5cafd96ff93ca458552a7f235200e1e8f39cb5/Error%2520Reporting) to the very bottom of **inc/init.php**? This will result in an error appearing on the page instead of it being killed off.

**Comment by ChanceSD** [comment]
Alright i added that, when seeing page source code, i found this:

<b>Warning</b>:  require_once(inc/classes/DOMDocument.php): failed to open stream: No such file or directory in <b>/usr/share/nginx/html/NamelessMC/inc/init.php</b> on line <b>40</b><br />
<br />
<b>Fatal error</b>:  require_once(): Failed opening required 'inc/classes/DOMDocument.php' (include_path='/usr/share/nginx/html/NamelessMC/inc/includes/html/library:.:/usr/share/pear:/usr/share/php') in <b>/usr/share/nginx/html/NamelessMC/inc/init.php</b> on line <b>40</b><br />

**Comment by samerton** [comment]
If you're running Debian/Ubuntu, the following SSH commands should do it:

sudo apt-get install php5-dom
sudo service apache2 restart

or, on CentOS

yum install php-xml
httpd restart

Hopefully that fixes the issue.

**Comment by ChanceSD** [comment]
That fixed it, thanks!
You should probably add that in the install guide (or did i miss it) to avoid future issues.

**Comment by samerton** [comment]
Glad it's fixed!

There are probably quite a few module checks missing from the installer, I'll add them in the future.

**Comment by ChanceSD** [comment]
Sorry if i'm getting annoying but it seems it isn't sending the validation emails, maybe i'm missing another module?

**Comment by samerton** [comment]
With version 0.4.0 you'll need to configure PHP via its php.ini to send email.

I've just done this on someone's installation, I installed sendmail with

sudo apt-get install sendmail
sudo sendmailconfig

and then I edited /etc/php5/apache2/php.ini and added the following

sendmail_path = "/usr/sbin/sendmail -t -f OUTGOING_EMAIL -i"

Replace OUTGOING_EMAIL with the email address you have set in the AdminCP's settings page, and then restart Apache.

**Comment by ChanceSD** [comment]
Thanks, after a long time i managed to get it working as i'm on nginx and centos here.
Only thing still an issue is minecraft username has to exist and some players don't have an account yet, but not a big deal.

**Comment by samerton** [comment]
The upcoming version 1.0 allows for non-premium player accounts, it'll be ready soon. You can check out the testing builds [here](https://github.com/NamelessMC/Nameless/).

**Comment by ChanceSD** [comment]
It still has a few bugs though, i can't access the Admin CP in 1.0 for example.
I will switch to the new one when it's ready though.
