### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by radekkas01** [samerton/NamelessMC#75]
Hi

I love your plugin but it would be amazing to be able to let users sign up and receive rewards in game with the new plugin your making (if possible). It would be cool if you could make it so you can enter the commands it executes when someone registers, such as /give <username> diamond 1 etc.

**Comment by TheWeirdEffect** [comment]
I also just realised that I cannot delete or change the ID of groups.

**Comment by samerton** [comment]
We'll look into this, thanks for the suggestion.

**Comment by samerton** [comment]
I've moved this to the repository for the upcoming Nameless plugin ([link to issue](https://github.com/NamelessMC/Nameless-Plugin/issues/34)).
