### ISSUE TITLE
Forum Lables and Registration

### ISSUE THREAD

**Issue by HaynoPrison** [samerton/NamelessMC#76]
**Forum Lables and Registration**

Hey there, I have only recently installed NamelessMC and it is great. I don't regret switching from Enjin at all. However, when a member creates a topic in the forum 'Helper Applications' they can add the custom labels I made (Pending, Accepted, Denied) and I was wondering if there was a way where only certain groups can apply labels.

Also, whenever a new user registers I have to manually Validate their account otherwise it says "Did you request a password reset?".

**Comment by samerton** [comment]
Hi,

At the moment there's no way to set permissions for labels unfortunately, this is something I'm aiming to add in the upcoming version 1.1.

As for the registration issue, you can head into the AdminCP -> Core -> Email and disable the "Enable mail account verification?" option; this will automatically validate users.
