### ISSUE TITLE
Issue upgrading from 1.0.3

### ISSUE THREAD

**Issue by tenten8401** [samerton/NamelessMC#77]
![Image of the error](http://tentencraft.net/pic/d/e0d16fffa.png)

Using nl1_ for database prefix

**Comment by samerton** [comment]
If you're upgrading from 1.0.3 to 1.0.4, all you will need to update via the AdminCP's "Update" tab. You'll get a package containing only the files needed to upload, avoiding the need to run through the installer again.

**Comment by tenten8401** [comment]
So I pretty much just broke my install

**Comment by samerton** [comment]
Replace your files with the 1.0.3 files, but remove the **pages/install.php** file. Input your MySQL settings into **core/config.php** and you should be back to normal.

**Comment by tenten8401** [comment]
Awesome. Thanks.
