### ISSUE TITLE
Set a group as administrator.

### ISSUE THREAD

**Issue by gp-Airee** [samerton/NamelessMC#79]
I want to have a separate rank for me and also have a rank for the owner with both of them being admin, how could I grant a group administrative rights?

**Comment by gp-Airee** [comment]
I took a quick look in the code and it looks as if it might be hardcoded in...

**Comment by samerton** [comment]
Depends on the Nameless version you're running. If you're running 0.4.1 from this repository it's hardcoded, however if you're running 1.x from the [new repository](https://github.com/NamelessMC/Nameless) you can give any group administrative rights.
