### ISSUE TITLE
after deletion of install.php blankpage

### ISSUE THREAD

**Issue by fishyboo** [samerton/NamelessMC#80]
I'm on a linux dedicated server running centos when I delete the install.php file everything just goes blank I have enabled mod rewrite in apache also. Thank you.

**Comment by samerton** [comment]
Can you ensure the permissions of the **cache** directory (and its subdirectories recursively) are writable?

**Comment by fishyboo** [comment]
I managed to fix everything for some odd reason when I moved the contents of the directory from /var/www/html/NamelessMC to /var/www/html/ the .htaccess file somehow got lost ? Anyways I just did nano .htacces in the /html directory and copy and pasted the .htaccess file from this github. Thanks anyway for your support awesome thing you have got going here !

**Comment by samerton** [comment]
Glad you managed to fix it :)
