### ISSUE TITLE
install folder

### ISSUE THREAD

**Issue by pyrominer2** [samerton/NamelessMC#81]
the install folder is not in zip

**Comment by samerton** [comment]
There isn't an install folder, it's a page named "install.php" within the pages folder. If you're getting a 404 not found error, don't move the file, but instead look at [this FAQ](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc).

**Comment by samerton** [comment]
I'm going to close this issue as it's down to a server configuration/file location issue, rather than an issue with Nameless itself. If you're still experiencing issues, feel free to reopen.
