### ISSUE TITLE
Add new custom pages

### ISSUE THREAD

**Issue by DataPools** [samerton/NamelessMC#82]
I want to add a custom page at the navigation menu or a link to another website on the navigation menu. 
How would I go about doing this?

**Comment by samerton** [comment]
You'd have to add the following line to the $main_navbar array of **core/includes/templates/navbar.php** (lines 26-29):
`'/link' => array(1 => 'Title', 2 => 'name')`

where:
- /link is either the internal link to the custom page, or the URL of your external page
- 'Title' is the link title (which will appear in the navbar)
- 'name' is the page name (the $page variable on your custom page, if you don't have one just leave it as name)
