### ISSUE TITLE
Pages are blank after installing

### ISSUE THREAD

**Issue by ChipDev** [samerton/NamelessMC#83]
Hey sam,
I installed Nameless and all was fine (thanks to you c: )
Now, when I visit the webpage/admin server etc...
It's blank.
At the bottom of init.php in the Core folder, I added
`ini_set('display_startup_errors',1); ini_set('display_errors',1); error_reporting(-1);`
And now it displays:
`Notice: Undefined offset: 0 in /var/www/html/pages/index.php on line 15

Notice: Trying to get property of non-object in /var/www/html/pages/index.php on line 15

Notice: Undefined offset: 0 in /var/www/html/pages/index.php on line 16

Notice: Trying to get property of non-object in /var/www/html/pages/index.php on line 16

Notice: Undefined offset: 0 in /var/www/html/pages/index.php on line 17

Notice: Trying to get property of non-object in /var/www/html/pages/index.php on line 17

Fatal error: Uncaught --> Smarty: unable to write file cache/templates_c/wrt576216675fac75_43220259 <-- thrown in /var/www/html/core/includes/smarty/sysplugins/smarty_internal_write_file.php on line 46`

If you can get this back to me later it would be much appreciated, thanks! 👍 :)

**Comment by samerton** [comment]
Hi,

Can you try the following SSH commands:

**sudo chown -R www-data:www-data /var/www/html/cache**

and also

**sudo chown -R www-data:www-data /var/www/html/core/includes/htmlpurifier**

**Comment by ChipDev** [comment]
OMG! It worked! Thank you so much, that worked.

Can you add this to the FAQ's for future problems? (I think others might appreciate that ;) )
Thanks for your help! Bye!

**Comment by samerton** [comment]
Glad it works, I've [added an explanation to the FAQ](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-white-screen-after-installing-namelessmc). :)
