### ISSUE TITLE
Namelessmc banner doesnt show non-25565 port

### ISSUE THREAD

**Issue by Wqrld** [samerton/NamelessMC#85]
Just what the title says, also this could already be fixed on github because a issue i made earlyer about the port not showing on the play page
Newest namelessmc at the moment
![image](https://cloud.githubusercontent.com/assets/13834197/16809442/a7b253c4-4920-11e6-9955-12a1b62fd4d1.png)
![image](https://cloud.githubusercontent.com/assets/13834197/16809443/a7e62d20-4920-11e6-9294-e921f81bb088.png)
![image](https://cloud.githubusercontent.com/assets/13834197/16809444/a7f6f5f6-4920-11e6-9e1d-8dbde7fba179.png)

**Comment by samerton** [comment]
Oops, was a simple typo. Fixed in https://github.com/NamelessMC/Nameless/commit/28a764bd9af95d1c0edaac53a65c10cc4a683acb over on the new repo.
