### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ghost** [samerton/NamelessMC#87]
1. Ports on Play
2. Multi Server Support

Thanks!

**Comment by LertuZUES** [comment]
there is multi server support

**Comment by LertuZUES** [comment]
and you can add ports on play manually
with the ip

**Comment by Sorro** [comment]
Just to let u guys know that this https://github.com/NamelessMC is the new community that has all of the namelessmc repo's.

**Comment by samerton** [comment]
I'll mark this as closed, as ports on the play page and multi server support are both possible using Nameless v1+, in the repo linked in the previous reply.
