### ISSUE TITLE
Can't proceed to upgrado

### ISSUE THREAD

**Issue by Legomix13** [samerton/NamelessMC#90]
Hi,

I'm stuck at requirements screen, I can't press nothink

**Comment by samerton** [comment]
On Ubuntu/Debian, try:

`sudo apt-get install php-xml`

(or php5-xml if that doesn't work)

or on CentOS try

`yum install php-xml`

before restarting Apache.

**Comment by samerton** [comment]
Were you able to resolve this issue? @Legomix13

**Comment by Legomix13** [comment]
Yes,thanks so much,if you want to see it I can send the ip

**Comment by samerton** [comment]
No problem, I'll go ahead and close this issue :)
