### ISSUE TITLE
Add a php function

### ISSUE THREAD

**Issue by ghost** [samerton/NamelessMC#92]
I want tu use php in my page to show the counter with online players but {php} {/php} is not supported and in the config $smarty->assign('online_players', $online_players); with {online_players} is also not working.

Please help me with it, it is a nice CMS but this is realy needed for me

**Comment by samerton** [comment]
Which Nameless version are you running, and which page are you adding the player counter to?

**Comment by ghost** [comment]
My Nameless version is 2.0 and I had tried in init.php, template.php, config.php, Smarty.class.php, header.php, scripts.php and navbar.php

**Comment by samerton** [comment]
Unfortunately, as Nameless version 2.0 is still in early pre-release stages, there is currently no server query included. 
It is something I am currently working on, and it will be possible in the upcoming second pre-release.

**Comment by ghost** [comment]
So, i need to wait? Or can i use an older version of Nameless?

**Comment by samerton** [comment]
You'd have to use the latest Nameless release ([v1.0.15](https://github.com/NamelessMC/Nameless/releases/tag/v1.0.15)), as that does include a server query.

**Comment by ghost** [comment]
Ok, thanks. I will try

**Comment by samerton** [comment]
No problem, I'll mark this as closed.

If you have any more questions, please feel free to ask in the [v1 repository](https://github.com/NamelessMC/Nameless) issue section.
